### ISSUE TITLE
Pipeline display improvements

### ISSUE THREAD

**Issue by adambrown1** [AG-Schumann/doberview2#16]
Suggest a few improvements to the pipeline display for easier and more intuitive use:
1. Show the pipeline description, for example when hovering over the pipeline or when clicking on an ⓘ next to its name. Some pipelines have non-obvious functionality. For example, "control_fast_cooling_scale_and_temp_no_isovac": the name suggests that the fast cooling is turned off depending on the dewar status ("scale") and whether the temperature target is being reached ("temp"). But it is not clear whether this is an or or and and, without reading through the eval nodes (even then it is not easy). This can be solved with a more explicit description of the pipeline.
2. Allow spaces in names (are they already?). Humans are not built for reading underscores. Related to this, remove the alarm_, control_, and convert_ at the start of names in the display.
3. Allow renaming of pipelines without spawning new ones. Humans make mistakes! I would suggest that the intuitive meaning of the "Save changes" button would be to change the name of the existing pipeline. A separate "Save copy" button could keep the existing functionality.
4. Out of curiosity, if I were to be naughty and create a pipeline with a non-standard prefix (like "adams_naughty_pipeline") would it simply vanish from the list, and is this desired? Do we want to force the alarm_ ... prefix by manually adding it to the name when saving and removing it when looking at the details? Or does this have nasty side effects? It would certainly mean it was impossible to change the pipeline type after creating it.

**Comment by adambrown1** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Website improvements](https://trello.com/c/mRtwXSjf/214-website-improvements)

**Comment by TiffanyLuce** [comment]
"Allow spaces in names (are they already?). Humans are not built for reading underscores. Related to this, remove the alarm_, control_, and convert_ at the start of names in the display."
-> Is replacing underscores by spaces only in the pipelines **display** a correct fix or should the actual name allow spaces in it at creation ?
