### ISSUE TITLE
Make new alarm button for sensors with existing pipelines

### ISSUE THREAD

**Issue by adambrown1** [AG-Schumann/doberview2#17]
We still want to be able to create alarms for sensors with pipelines (non-alarm ones at least)

**Comment by adambrown1** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Website improvements](https://trello.com/c/mRtwXSjf/214-website-improvements)

**Comment by TiffanyLuce** [comment]
Would making the "Make new alarm" button appear for all sensors (even those with already existing alarm pipelines) be a correct fix ?

**Comment by adambrown1** [comment]
> Would making the "Make new alarm" button appear for all sensors (even those with already existing alarm pipelines) be a correct fix ?

Yes and I have already used it several times!
