### ISSUE TITLE
Swap pipelines and plot

### ISSUE THREAD

**Issue by adambrown1** [AG-Schumann/doberview2#35]
In the sensor details dialogue, what about swapping "Pipelines involving this sensor" and "Recent history" so that the plot is immediately visible even when there is a long list of pipelines (e.g. M_TS_01)?

**Comment by TiffanyLuce** [comment]
Do you like it this way ? I think it's nice especially on the phone!
I also moved the 'Make new alarm' button to the top of the pipeline list to make it easier with this display but can put it back at the end if you prefer.

**Comment by adambrown1** [comment]
Very nice! I like it very much, including the reordering, I just might change the labels “clean” and “better?” to something more descriptive!
